; PlatformIO Project Configuration File

[env]
platform = renesas-ra
board = uno_r4_minima
framework = arduino
monitor_speed = 115200


; ===== Basic motor spinning test =====
[env:motor_spinning]
build_src_filter =
    -<*>
    +<motor_spinning_base_code.cpp>


; ===== User input position controller =====
[env:position_follower]
build_src_filter =
    -<*>
    +<user_input_position_follower.cpp>

; ===== Stiction value finder =====
[env:stiction_value_finder]
build_src_filter =
    -<*>
    +<stiction_tester.cpp>